version: '3.1'

services:
  db:
    image: mysql:latest
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
